title: <p align = 'center'> Abhishek Hegde </p>
logo: /assets/img/logo.png
description: <p align = 'center'> I am currently working in Accenture Solutions pvt ltd. I comepleted my undergrad from Dayananda Sagar College of Engineering and pursuing my masters from University of Arizona.
https://github.com/AbhyNeptune/Course </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
